### ISSUE TITLE
Unintuitives hinzufügen von neuen Expressions, Default Werte komisch

### ISSUE THREAD

**Issue by ChiaraLisa** [JoanaP1997/PSE#6]

**Comment by JoanaP1997** [comment]
https://github.com/JoanaP1997/PSE/commit/e2d888e127b2ddc47def33b1d5746c47bf47b328
Default Werte geändert

**Comment by JoanaP1997** [comment]
cecd28306446a74c99c2a869d66b665708b1cf32
Expressions können jetzt intuitiv über einen Button hinzugefügt werden
